config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'Parent', :controllers => { :registrations => "registrations" }

  root 'welcome#index'

  authenticate :user do
    resources :users, only: [:index, :show] do
      resources :profiles
    end

    resources :dates, class_name: 'Playdate', controller: :playdates do
      resources :messages, only: [:create]
      resources :charges, only: [:new, :create]
    end

    post '/dates/:id/accept' => 'playdates#accept_invitation'
    post '/dates/:id/confirm' => 'playdates#confirm_date'
    post '/dates/:id/delete' => 'playdates#delete_event'
    post '/dates/:id/movie' => 'playdates#add_movie'

    resources :interests, only: [:index, :create]
    resources :values, only: [:index, :create]

    get '/filters' => 'filters#filter_matches'

    get '/filters/autocomplete/interests' => 'filters#autocomplete_interest_name'
    get '/filters/autocomplete/values' => 'filters#autocomplete_value_name'

    get '/users/:id/messages' => 'users#messages'

    post 'twilio/voice' => 'twilio#voice'
    post 'twilio/status' => 'twilio#status'
    post 'charges/notify' => 'charges#notify'

    post '/' => 'welcome#change_child'

  end

end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  belongs_to :initiator, class_name: 'Child'
  belongs_to :recipient, class_name: 'Child'
  belongs_to :experience
  belongs_to :movie

  validates :initiator_id, :recipient_id, presence: true

  ##### Conversation-specific block
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :initiator_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.initiator_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (initiator_id,recipient_id) do
    where("(conversations.initiator_id = ? AND conversations.recipient_id =?) OR (conversations.initiator_id = ? AND conversations.recipient_id =?)", initiator_id,recipient_id, recipient_id, initiator_id)
  end
  ##### End conversation-specific block

  def total_cost_per_person
    self.experience.nil? ? experience_cost = 0 : experience_cost = self.experience.price_per_person
    self.movie.nil? ? movie_cost = 0 : movie_cost = self.movie.price_per_person
    total_cost = experience_cost + movie_cost
  end

  def both_parents_accepted?
    return self.recipient_accepted #implicit that the initiator has accepted
  end

  def both_parents_confirmed? #this also implies they have both paid
    if both_parents_accepted?
      return (self.initiator_confirmed && self.recipient_confirmed)
    else
      return false
    end
  end

  def both_parents_paid?
    if (both_parents_accepted? && both_parents_confirmed?) #ensure other two conditions are already met
      return (self.initiator_paid && self.recipient_paid)
    else
      return false
    end
  end

  def status #order is important here
    if both_parents_paid?
      return 'paid'
    elsif both_parents_confirmed?
      return 'confirmed'
    elsif both_parents_accepted?
      return 'accepted'
    else
      return 'pending'
    end
  end

  def event_selected?
    !(self.experience.nil?) || !(self.movie.nil?)
  end

  def two_events_selected?
    !(self.experience.nil?) && !(self.movie.nil?)
  end

  def first_event_location
    return "No events selected" if (self.experience.nil? && self.movie.nil?)
    playdate_locations = []
    playdate_locations << self.experience.venue if self.experience
    playdate_locations << self.movie.venue if self.movie
    playdate_first_location = playdate_locations.min
  end

  def last_event_location
    return "No events selected" if (self.experience.nil? && self.movie.nil?)
    playdate_locations = []
    playdate_locations << self.experience.venue if self.experience
    playdate_locations << self.movie.venue if self.movie
    playdate_last_location = playdate_locations.max
  end

  def first_event_datetime
    return "No events selected" if (self.experience.nil? && self.movie.nil?)
    playdate_times = []
    playdate_times << self.experience.experience_at if self.experience
    playdate_times << self.movie.movie_at if self.movie
    playdate_first_datetime = playdate_times.min
  end

  def last_event_datetime
    return "No events selected" if (self.experience.nil? && self.movie.nil?)
    playdate_times = []
    playdate_times << self.experience.experience_at if self.experience
    playdate_times << self.movie.movie_at if self.movie
    playdate_last_datetime = playdate_times.max
  end

  def first_event_datetime_as_str
    self.first_event_datetime.strftime("%A, %B %d, at %I:%M %p")
  end

  def last_event_datetime_as_str
    self.last_event_datetime.strftime("%A, %B %d, at %I:%M %p")
  end

  def you_accepted?(current_user)
    if current_user.initiated_date?(self) #you are the initiator
      return self.initiator_accepted
    elsif (current_user.initiated_date?(self) == false) #you are the recipient
      return self.recipient_accepted
    else
      puts "You are not associated with this date"
      return nil
    end
  end

  def other_accepted?(current_user)
    if current_user.initiated_date?(self) #you are the initiator
      return self.recipient_accepted
    elsif (current_user.initiated_date?(self) == false) #you are the recipient
      return self.initiator_accepted
    else
      puts "You are not associated with this date"
      return nil
    end
  end

  def you_confirmed?(current_user)
    if current_user.initiated_date?(self) #you are the initiator
      return self.initiator_confirmed
    elsif (current_user.initiated_date?(self) == false) #you are the recipient
      return self.recipient_confirmed
    else
      puts "You are not associated with this date"
      return nil
    end
  end

  def other_confirmed?(current_user)
    if current_user.initiated_date?(self) #you are the initiator
      return self.recipient_confirmed
    elsif (current_user.initiated_date?(self) == false) #you are the recipient
      return self.initiator_confirmed
    else
      puts "You are not associated with this date"
      return nil
    end
  end

  def you_paid?(current_user)
    if current_user.initiated_date?(self) #you are the initiator
      return self.initiator_paid
    elsif (current_user.initiated_date?(self) == false) #you are the recipient
      return self.recipient_paid
    else
      puts "You are not associated with this date"
      return nil
    end
  end

  def other_paid?(current_user)
    if current_user.initiated_date?(self) #you are the initiator
      return self.recipient_paid
    elsif (current_user.initiated_date?(self) == false) #you are the recipient
      return self.initiator_paid
    else
      puts "You are not associated with this date"
      return nil
    end
  end

end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/views/playdates/_chat.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
    <h2><%= @receiver.first_name %>'s Mom</h2>
  </div>
  <br clear="all"/>
</div>

<div class="chatboxinput">
  <%= form_for(:message, url: date_messages_path(@playdate), remote: true, html: {id: "conversation_form_#{@playdate.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", placeholder: "Add a personal message here.", "data-cid" => @playdate.id %>
      <%= f.submit "Send Message", class: "chatboxsubmit" %>
  <% end %>
</div>

<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages.reverse %>
  <% end %>
</div>
 
<%= subscribe_to date_path(@playdate) %>

app/views/playdates/_date_participant_image_template.html.erb
<script id="date-participant-image-template" type="x-handlebars-template">
<div class="pf-modal-container container hidden">
  <div class="row">

    <div id="gallery-wrap" class="pf-images-wrapper slick-carousel col span_5">
      <img src="{{profile.pf_image_1}}" />
      <img src="{{profile.pf_image_2}}" />
      <img src="{{profile.pf_image_3}}" />
      <img src="{{profile.pf_image_4}}" />
      <img src="{{profile.pf_image_5}}" />
    </div>

    <div class="pf-basic-info-wrapper col span_7">
      <h1>{{profile.first_name}} {{profile.last_name}}</h1>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6"><i class="fa fa-birthday-cake category-icon"></i> {{age}} years old</div>
        <div class="pf-basic-info-cell col span_6"><i class="fa fa-globe category-icon"></i> {{profile.city}}, {{profile.state}}</div>
      </div>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6">
          <i class="fa fa-venus-mars category-icon"></i>
          {{#ifCond profile.gender "male"}}
            <i class="fa fa-male"></i>
          {{else}}
            {{#ifCond profile.gender "female"}}
              <i class="fa fa-female"></i>
            {{else}}
              <i class="fa fa-transgender"></i>
            {{/ifCond}}
          {{/ifCond}}
           seeking
          {{#ifCond profile.sexual_preference "men"}}
            <i class="fa fa-male"></i>
          {{else}}
            {{#ifCond profile.sexual_preference "women"}}
              <i class="fa fa-female"></i>
            {{else}}
              <i class="fa fa-female"></i>
              <i class="fa fa-male"></i>
            {{/ifCond}}
          {{/ifCond}}
        </div>

        <div class="pf-basic-info-cell col span_6">
        <i class="fa fa-eye category-icon"></i>
        {{#if profile.religion}}
          {{profile.religion}}
        {{else}}
          Religion not specified
        {{/if}}
        </div>
      </div>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6">
          <i class="fa fa-paw category-icon"></i>
          {{profile.pets}}
        </div>
        <div class="pf-basic-info-cell col span_6">
          <i class="fa fa-heartbeat category-icon"></i>
          {{#if profile.smoke}}
            Smoker
          {{else}}
            Non-smoker
          {{/if}}
        </div>
      </div>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6"><a href="{{profile.linkedin_url}}"><i class="fa fa-linkedin-square category-icon"></i> LinkedIn</a></div>
        <div class="pf-basic-info-cell col span_6"><a href="{{profile.facebook_url}}"><i class="fa fa-facebook-square category-icon"></i> Facebook</a></div>
      </div>

      <div class="pf-bio-wrapper">
        <h3>About {{profile.first_name}}</h3>
        <p class="pf-bio-content">{{profile.bio}}</p>
      </div>

    </div>

  </div>

  <div class="row">
    <h2>The Good Stuff</h2>
  </div>

  <div class="row">

    <div class="pf-box-wrapper col span_4">
      <div class="flip-wrapper">
        <figure class="effect-dexter pf-box pf-box-front">
          <figcaption>
            <h3>Embarrassing Moments</h3>
            <p>Click to read more!</p>
          </figcaption>
        </figure>
        <div class="pf-box pf-box-back hidden">
          <div class="pf-embarrass-moment">{{profile.embarrassing_moment}}</div>
        </div>
      </div>
    </div>

    <div class="pf-box-wrapper col span_4">
      <div class="flip-wrapper">
        <figure class="effect-dexter pf-box pf-box-front">
          <figcaption>
            <h3>Interests</h3>
            <p>Click to read more!</p>
          </figcaption>
        </figure>
        <div class="pf-box pf-box-back hidden">
          {{#each interests}}
            <div class="pf-interest-btn">{{this.name}}</div>
          {{/each}}
        </div>
      </div>
    </div>

    <div class="pf-box-wrapper col span_4">
      <div class="flip-wrapper">
        <figure class="effect-dexter pf-box pf-box-front">
          <figcaption>
            <h3>Values</h3>
            <p>Click to read more!</p>
          </figcaption>
        </figure>
        <div class="pf-box pf-box-back hidden">
          {{#each values}}
            <div class="pf-interest-btn">{{this.name}}</div>
          {{/each}}
        </div>
      </div>
    </div>

  </div>
</div>
</script>

app/views/playdates/_date_status_box.html.erb
      <div class="status-box row">
        <div class="date-status-header">
          <p>DATE STATUS</p>
        </div>
        <div class="col span_6">
          <div class="date-status-parent-name">
            <% if playdate.initiator.parent.id == current_user.id %>
              <span>You</span>
            <% else %>
              <span><%= playdate.initiator.parent.first_name %></span>
            <% end %>
          </div>
          <div class="date-status-table">
            <div class="date-status-row">
              <i class="fa fa-check-circle"></i>
              <p>Initiated</p>
            </div>
            <div class="date-status-row">
              <i id="initiator-confirmed" class="<%= playdate.initiator_confirmed ? 'fa fa-check-circle' : 'fa fa-circle-thin' %>"></i>
              <p>Confirmed</p>
            </div>
            <div class="date-status-row">
              <i id="initiator-paid" class="<%= playdate.initiator_paid ? 'fa fa-check-circle' : 'fa fa-circle-thin' %>"></i>
              <p>Paid</p>
            </div>
          </div>
        </div>

        <div class="col span_6">
          <div class="date-status-parent-name">
            <% if playdate.recipient.parent.id == current_user.id %>
              <span>You</span>
            <% else %>
              <span><%= playdate.recipient.parent.first_name %></span>
            <% end %>
          </div>
          <div class="date-status-table">
            <div class="date-status-row">
              <i id="recipient-accepted" class="<%= playdate.recipient_accepted ? 'fa fa-check-circle' : 'fa fa-circle-thin' %>"></i>
              <p>Accepted</p>
            </div>
            <div class="date-status-row">
              <i id="recipient-confirmed" class="<%= playdate.recipient_confirmed ? 'fa fa-check-circle' : 'fa fa-circle-thin' %>"></i>
              <p>Confirmed</p>
            </div>
            <div class="date-status-row">
              <i id="recipient-paid" class="<%= playdate.recipient_paid ? 'fa fa-check-circle' : 'fa fa-circle-thin' %>"></i>
              <p>Paid</p>
            </div>
          </div>
        </div>

      </div>

app/views/playdates/_experience_card.html.erb
<div class="date-experience-card row">
  <div class="experience-image col span_5">
    <figure class="effect-bubba">
      <img src="<%= experience.image %>" />
      <figcaption>
        <h3><%= experience.venue %></h3>
        <p><%= experience.desc_summary %></p>
      </figcaption>
    </figure>
  </div>
  <div class="experience-details col span_7">

<!--  this is where the delete button on the card in the food and drink section appears - it happens both in the selected event container AND the food/drink section because it's the same event -->

    <div class="exp-detail-item">
      <i class="fa fa-calendar"></i>
      <p><%= experience.experience_at_formatted %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-street-view"></i>
      <p><%= experience.address %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-cutlery"></i>
      <p><%= experience.desc_note_1 %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-leaf"></i>
      <p><%= experience.desc_note_2 %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-smile-o"></i>
      <p><%= experience.desc_note_3 %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-money"></i>
      <p>$<%= experience.price_per_person %> / person</p>
    </div>
  </div>

  <div class="select-experience-btn <%= 'hidden' if @playdate.experience == experience %>">
    <a href="/dates/<%= @playdate.id %>" data-experience-id="<%= experience.id %>">Choose Experience</a>
  </div>
</div>

app/views/playdates/_experience_card_template.html.erb
<script type="x-handlebars-template" class="date-experience-card-template">
<div class="date-experience-card row">
  <div class="experience-image col span_5">
    <figure class="effect-bubba">
      <img src="{{experience.image}}" />
      <figcaption>
        <h3>{{experience.venue}}</h3>
        <p>{{experience.desc_summary}}</p>
      </figcaption>
    </figure>
  </div>
  <div class="experience-details col span_7">
    {{#ifCond deleteButton true}}
    	<a href="/dates/{{playdate.id}}/delete" data-experience-id="{{experience.id}}" class="selected-experience-delete-btn"><i class="close-icon fa fa-times"></i></a>
    {{/ifCond}}

    <div class="exp-detail-item">
      <i class="fa fa-calendar"></i>
      <p>{{experienceData.formattedExperienceDate}}</p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-street-view"></i>
      <p>{{experience.address}}</p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-cutlery"></i>
      <p>{{experience.desc_note_1}}</p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-leaf"></i>
      <p>{{experience.desc_note_2}}</p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-smile-o"></i>
      <p>{{experience.desc_note_3}}</p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-money"></i>
      <p>${{experience.price_per_person}} / person</p>
    </div>
  </div>
</div>
</script>

app/views/playdates/_initiator_profile_template.html.erb
<script id="initiator-profile-template" type="x-handlebars-template">
<div class="pf-modal-container container hidden">
  <div class="row">

    <div id="gallery-wrap" class="pf-images-wrapper slick-carousel col span_5">
      <img src="{{profile.pf_image_1}}" />
      <img src="{{profile.pf_image_2}}" />
      <img src="{{profile.pf_image_3}}" />
      <img src="{{profile.pf_image_4}}" />
      <img src="{{profile.pf_image_5}}" />
    </div>

    <div class="pf-basic-info-wrapper col span_7">
      <h1>{{profile.first_name}} {{profile.last_name}}</h1>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6"><i class="fa fa-birthday-cake category-icon"></i> {{age}} years old</div>
        <div class="pf-basic-info-cell col span_6"><i class="fa fa-globe category-icon"></i> {{profile.city}}, {{profile.state}}</div>
      </div>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6">
          <i class="fa fa-venus-mars category-icon"></i>
          {{#ifCond profile.gender "male"}}
            <i class="fa fa-male"></i>
          {{else}}
            {{#ifCond profile.gender "female"}}
              <i class="fa fa-female"></i>
            {{else}}
              <i class="fa fa-transgender"></i>
            {{/ifCond}}
          {{/ifCond}}
           seeking
          {{#ifCond profile.sexual_preference "men"}}
            <i class="fa fa-female"></i>
          {{else}}
            {{#ifCond profile.sexual_preference "women"}}
              <i class="fa fa-male"></i>
            {{else}}
              <i class="fa fa-female"></i>
              <i class="fa fa-male"></i>
            {{/ifCond}}
          {{/ifCond}}
        </div>

        <div class="pf-basic-info-cell col span_6">
        <i class="fa fa-eye category-icon"></i>
        {{#if profile.religion}}
          {{profile.religion}}
        {{else}}
          Religion not specified
        {{/if}}
        </div>
      </div>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6">
          <i class="fa fa-paw category-icon"></i>
          {{profile.pets}}
        </div>
        <div class="pf-basic-info-cell col span_6">
          <i class="fa fa-heartbeat category-icon"></i>
          {{#if profile.smoke}}
            Smoker
          {{else}}
            Non-smoker
          {{/if}}
        </div>
      </div>

      <div class="pf-basic-info-row">
        <div class="pf-basic-info-cell col span_6"><a href="{{profile.linkedin_url}}"><i class="fa fa-linkedin-square category-icon"></i> LinkedIn</a></div>
        <div class="pf-basic-info-cell col span_6"><a href="{{profile.facebook_url}}"><i class="fa fa-facebook-square category-icon"></i> Facebook</a></div>
      </div>

      <div class="pf-bio-wrapper">
        <h3>About {{profile.first_name}}</h3>
        <p class="pf-bio-content">{{profile.bio}}</p>
      </div>

    </div>

  </div>

  <div class="row">
    <h2>The Good Stuff</h2>
  </div>

  <div class="row">

    <div class="pf-box-wrapper col span_4">
      <div class="flip-wrapper">
        <figure class="effect-dexter pf-box pf-box-front">
          <figcaption>
            <h3>Embarrassing Moments</h3>
            <p>Click to read more!</p>
          </figcaption>
        </figure>
        <div class="pf-box pf-box-back hidden">
          <div class="pf-embarrass-moment">{{profile.embarrassing_moment}}</div>
        </div>
      </div>
    </div>

    <div class="pf-box-wrapper col span_4">
      <div class="flip-wrapper">
        <figure class="effect-dexter pf-box pf-box-front">
          <figcaption>
            <h3>Interests</h3>
            <p>Click to read more!</p>
          </figcaption>
        </figure>
        <div class="pf-box pf-box-back hidden">
          {{#each interests}}
            <div class="pf-interest-btn">{{this.name}}</div>
          {{/each}}
        </div>
      </div>
    </div>

    <div class="pf-box-wrapper col span_4">
      <div class="flip-wrapper">
        <figure class="effect-dexter pf-box pf-box-front">
          <figcaption>
            <h3>Values</h3>
            <p>Click to read more!</p>
          </figcaption>
        </figure>
        <div class="pf-box pf-box-back hidden">
          {{#each values}}
            <div class="pf-interest-btn">{{this.name}}</div>
          {{/each}}
        </div>
      </div>
    </div>

  </div>
</div>
</script>

app/views/playdates/_movie_card.html.erb
<div class="date-movie-card row">
  <div class="movie-image col span_5">
    <figure class="effect-bubba">
      <img src="<%= movie.image %>" />
      <figcaption>
        <h3><%= experience.venue %></h3>
        <p><%= experience.desc_summary %></p>
      </figcaption>
    </figure>
  </div>
  <div class="movie-details col span_7">
    <% if (@playdate.movie == movie) && !(@playdate.you_confirmed?(current_user)) %>
      <i class="close-icon fa fa-times"></i>
    <% end %>


    <div class="exp-detail-item">
      <i class="fa fa-calendar"></i>
      <p><%= experience.experience_at_formatted %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-street-view"></i>
      <p><%= experience.address %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-cutlery"></i>
      <p><%= experience.desc_note_1 %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-leaf"></i>
      <p><%= experience.desc_note_2 %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-smile-o"></i>
      <p><%= experience.desc_note_3 %></p>
    </div>
    <div class="exp-detail-item">
      <i class="fa fa-money"></i>
      <p>$<%= experience.price_per_person %> / person</p>
    </div>
  </div>

  <% unless @playdate.experience == experience %>
    <div class="select-experience-btn">
      <a href="/dates/<%= @playdate.id %>?exp_id=<%= experience.id %>">Choose Experience</a>
    </div>
  <% end %>
</div>

app/views/playdates/_movie_card_template.html.erb
<script type="x-handlebars-template" class="date-movie-card-template">
<div class="date-movie-card row">
  <div class="movie-image col span_5">
    <figure class="">
      <img src="{{movie.image}}" />
      <figcaption>
      </figcaption>
    </figure>
  </div>
  <div class="movie-details col span_7">
    {{#ifCond deleteButton true}}
      <a href="/dates/{{playdate.id}}" data-movie-id="{{movie.id}}" class="selected-movie-delete-btn"><i class="close-icon fa fa-times"></i></a>
    {{/ifCond}}

    <div class="movie-detail-item">
      <i class="fa fa-film"></i>
      <p><strong>{{movie.title}}</strong></p>
    </div>
    <div class="movie-detail-item">
      <i class="fa fa-calendar"></i>
      <p>{{movieData.formattedMovieDate}}</p>
    </div>
    <div class="movie-detail-item">
      <i class="fa fa-street-view"></i>
      <p>{{movie.address}}</p>
    </div>
    <div class="movie-detail-item">
      <i class="fa fa-user"></i>
      <p><em>Director:</em> {{movie.director}}</p>
    </div>
    <div class="movie-detail-item">
      <i class="fa fa-info-circle"></i>
      <p><em>Description:</em> {{movieData.movieDescriptionClipped}}</p>
    </div>
    <div class="movie-detail-item">
      <i class="fa fa-star"></i>
      <p>{{movieData.movieRatingFormatted}}</p>
    </div>
    <div class="movie-detail-item">
      <i class="fa fa-money"></i>
      <p>${{movie.price_per_person}} / person</p>
    </div>
  </div>
</div>
</script>

app/views/playdates/_movie_row.html.erb
<div class="movie row">
  <div id="movie-wrap" class= "col span_12">
    <% @names_and_ids.each do |movie| %>
    <div class= "movie-flip">
      <img class="movie-poster mv-box-front" alt = "<%= movie.first %>" src="<%= movie.last[:movie_poster]%>">
      <div class="movie-poster mv-box-back hidden">
        <a href="#"><div class="add-to-package">Add to Package</div></a>
        <h3><%= movie.first %></h3>
        <ul>
          <li class="mv-synopsis"><span class="boldify blueify">Synopsis: </span><%= truncate(movie.last[:synopsis], length: 70, separator: ' ') %></li>
          <li class="mv-mpaa-rating"><span class="boldify blueify">Rating: </span><%= movie.last[:mpaa] %></li>
          <li class="mv-release-date"><span class="boldify blueify">Release Date: </span><%= movie.last[:release_date] %></li>
          <li class="mv-runtime"><span class="boldify blueify">Runtime: </span><%= movie.last[:runtime] %></li>
          <li class="mv-rt-score"><span class="boldify blueify">RT score: </span><%= movie.last[:rating] %>
          </li>

        </ul>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/playdates/new.html.erb
<div class="playdate-container debug">
  <div class = "status row">
    <div class="col span_12">
      <h1> Status: Pending//Declined//Confirmed</h1>
    </div>
  </div>

  <div class=" col date-data span_8 debug">
    <div class="movie row debug">
      <h3> Budget:</h3>
      <h3> Date/Time:</h3>
    </div>

    <div class="movie row debug">
      <h2> Plan the Date: </h2>
      <h3> Movies </h3>

    </div>

    <div class="restaurant row debug">
      <h2> Restaurants: </h2>
    </div>

    <div class="calendar row debug">
      <h2> Calendar: </h2>
    </div>

  </div>

  <div class=" chat-data col span_4 debug">
    Chat stuff
  </div>

</div>