config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'Parent', :controllers => { :registrations => "registrations" }

  root 'welcome#index'

  authenticate :user do
    resources :users, only: [:index, :show] do
      resources :profiles
    end

    resources :dates, class_name: 'Playdate', controller: :playdates do
      resources :messages, only: [:create]
      resources :charges, only: [:new, :create]
    end

    post '/dates/:id/accept' => 'playdates#accept_invitation'
    post '/dates/:id/confirm' => 'playdates#confirm_date'
    post '/dates/:id/delete' => 'playdates#delete_event'
    post '/dates/:id/movie' => 'playdates#add_movie'

    resources :interests, only: [:index, :create]
    resources :values, only: [:index, :create]

    get '/filters' => 'filters#filter_matches'

    get '/filters/autocomplete/interests' => 'filters#autocomplete_interest_name'
    get '/filters/autocomplete/values' => 'filters#autocomplete_value_name'

    get '/users/:id/messages' => 'users#messages'

    post 'twilio/voice' => 'twilio#voice'
    post 'twilio/status' => 'twilio#status'
    post 'charges/notify' => 'charges#notify'

    post '/' => 'welcome#change_child'

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new

	end

	def create
		date = Playdate.find(params[:date_id])
		@amount = (date.total_cost_per_person * 100) # amount in cents

		customer = Stripe::Customer.create(
			email:  params[:stripeEmail],
			card:   params[:stripeToken]
		)

		charge = Stripe::Charge.create(
		  customer:    customer.id,
		  amount:      @amount,
		  description: date.id,
		  currency:    'usd'
		)

		if current_user == date.initiator.parent
			date.initiator_paid = true
      date.save!
		elsif current_user == date.recipient.parent
			date.recipient_paid = true
      date.save!
    end

		if date.status == 'paid'
			notify(date)
		end

		redirect_to "/users/#{current_user.id}?message=paid&date=#{date.id}"

		rescue Stripe::CardError, Stripe::InvalidRequestError => e
		  flash[:error] = e.message
		  redirect_to date_path(date)
	end

	def notify(date)
		client = Twilio::REST::Client.new ENV['twilio_account_sid'], ENV['twilio_auth_token']

		message_to_initiator = client.messages.create(
			:from => '+14242653879',
			:to => "#{date.initiator.phone.gsub('-','')}",
			:body => "Your parent has set you up on a date with #{date.recipient.first_name}",
			# :media_url => "#{date.recipient.default_pf}"
			# status_callback: request.base_url + '/twilio/status'
			)

		message_to_recipient = client.messages.create(
			:from => '+14242653879',
			:to => "#{date.recipient.phone.gsub('-','')}",
			:body => "Your parent has set you up on a date with #{date.initiator.first_name}",
			# :media_url => "#{date.initiator.default_pf}"
			)
	end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_new.html.erb
<%= form_tag date_charges_path(@playdate) do %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Purchase Date"
          data-amount="<%= @playdate.total_cost_per_person * 100 %>"
          data-date></script>
<% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $50.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="5000"></script>
<% end %>