config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: 'Parent', :controllers => { :registrations => "registrations" }

  root 'welcome#index'

  authenticate :user do
    resources :users, only: [:index, :show] do
      resources :profiles
    end

    resources :dates, class_name: 'Playdate', controller: :playdates do
      resources :messages, only: [:create]
      resources :charges, only: [:new, :create]
    end

    post '/dates/:id/accept' => 'playdates#accept_invitation'
    post '/dates/:id/confirm' => 'playdates#confirm_date'
    post '/dates/:id/delete' => 'playdates#delete_event'
    post '/dates/:id/movie' => 'playdates#add_movie'

    resources :interests, only: [:index, :create]
    resources :values, only: [:index, :create]

    get '/filters' => 'filters#filter_matches'

    get '/filters/autocomplete/interests' => 'filters#autocomplete_interest_name'
    get '/filters/autocomplete/values' => 'filters#autocomplete_value_name'

    get '/users/:id/messages' => 'users#messages'

    post 'twilio/voice' => 'twilio#voice'
    post 'twilio/status' => 'twilio#status'
    post 'charges/notify' => 'charges#notify'

    post '/' => 'welcome#change_child'

  end

end

app/views/layouts/_devise_login.html.erb
<div class= "devise-container">
  <h2>Log in</h2>

  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>

    <div class="field text-input">
      <%= f.email_field :email, autofocus: true, placeholder: "email" %>
    </div>

    <div class="field text-input">
      <%= f.password_field :password, autocomplete: "off", placeholder: "password" %>
    </div>

    <% if devise_mapping.rememberable? -%>
      <div class="field">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>
    <% end -%>

    <div class="actions">
      <%= f.submit "Log in", class: "submit-btn" %>
    </div>
  <% end %>

  <%= render "user/shared/links" %>
</div>

app/views/layouts/_devise_new_password.html.erb
<div class="devise-container">
  <h2>Forgot your password?</h2>

  <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
    <%= devise_error_messages! %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "Email Instructions", class: "submit-btn" %>
    </div>
  <% end %>

  <%= render "user/shared/links" %>
</div>

app/views/layouts/_devise_signup.html.erb
<div class = "devise-container">
  <h2>Sign up</h2>

  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <div class="devise-errors"><%= devise_error_messages! %></div>

    <div class="field text-input">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, autofocus: true, placeholder: "First Name" %>
    </div>

    <div class="field text-input">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, autofocus: true, placeholder: "Last Name" %>
    </div>

    <div class="field text-input">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field text-input">
      <%= f.label :password %>
      <% if @validatable %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field text-input">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up", class: "submit-btn" %>
    </div>
  <% end %>

  <%= render "user/shared/links" %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="logo"><a href="/">Bring Home to Mom</a></div>
  <ul>
    <% if user_signed_in? %>
      <li class="notification">
        <a class="dashboard" href="/users/<%= current_user.id %>" >(<%= current_user.pending_dates.count + current_user.accepted_dates.count %>) Dashboard</a>
        <%= render partial: 'layouts/notification_dropdown' %>
      </li>
    	<li><%= link_to "Log Out", "/users/sign_out", method: 'delete', class:"logout-button" %><li>
    <% elsif request.env['PATH_INFO'] == "/" %>
			<li><a href="#" class="login-btn login-btn-nav">Log In</a></li>
			<li><a href="#" class="signup-btn signup-btn-nav">Sign Up</a></li>
		<% end %>
  </ul>
</nav>
  <div class="navbar-filler">
</div>

app/views/layouts/_notification_date_preview.erb
<div class="date-preview row">
  <a href="/dates/<%= date.id %>">
    <div class="your-child-photo col span_3">
      <img src="<%= user.my_child(date).default_pf %>" />
    </div>
    <div class="date-details col span_6">
      <ul>
        <% if user.initiated_date?(date) %>
          <li>You asked to introduce <%= user.my_child(date).first_name %> to <span><%= user.other_child(date).first_name %></span></li>
        <% else %>
          <li><span><%= user.other_child(date).parent.first_name %></span> asked to introduce <span><%= user.other_child(date).first_name %></span> to <%= user.my_child(date).first_name %></li>
        <% end %>
      </ul>
    </div>
    <div class="other-child-photo col span_3">
      <img src="<%= user.other_child(date).default_pf %>" />
    </div>
  </a>
</div>

app/views/layouts/_notification_dropdown.html.erb
<div class="notification-dropdown dates-rows-wrapper">
  <% if current_user.pending_dates.any? %>
    <div class="dashboard-section-header">
      Pending Date Requests
    </div>
    <% current_user.pending_dates.each do |date| %>
      <%= render partial: 'layouts/notification_date_preview', locals: {date: date, user: current_user} %>
    <% end %>
  <% end %>

  <% if current_user.accepted_dates.any? %>
    <div class="dashboard-section-header">
      Planning Phase
    </div>
    <% current_user.accepted_dates.each do |date| %>
      <%= render partial: 'layouts/notification_date_preview', locals: {date: date, user: current_user} %>
    <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bring Home To Mom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- [TODO]: DOWNLOAD FONTS AND INCLUDE IN ASSET PIPELINE -->
  <link href='http://fonts.googleapis.com/css?family=Questrial|Lato:300,400|Arvo:400,700|Josefin+Sans:300,400,600,700|Vollkorn|Open+Sans:400,700,600,300,800|Montserrat:400,700|Lobster:400|Signika:400,600,700|Raleway:400,800,900,700,600,500' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
</head>
<body>

	<header class="app-header">
    <%= render partial: 'layouts/navbar' %>
	</header>
	<%= yield %>
  <script src="https://checkout.stripe.com/checkout.js"></script>

</body>
</html>

app/views/layouts/devise.html.erb
<div class="li-lo-container">
  <header class="li-lo-header">
      <%= render partial: 'layouts/navbar' %>
  </header>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <link href='http://fonts.googleapis.com/css?family=Lobster:400' rel='stylesheet' type='text/css'>
<%= render 'layouts/devise_signup' if request.env['PATH_INFO'] == "/users" %>
<%= render 'layouts/devise_login' if request.env['PATH_INFO'] == "/users/sign_in"%>
<%= render 'layouts/devise_new_password' if request.env['PATH_INFO'] == "/users/password/new"%>

</div>

<!-- render login/signup page if path is login/signup, respectively. (overriding devise)
 -->